[project]
name = "orchestrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyzmq==25.1.1",
    "requests==2.31.0",
    "alicepi-proto @ ../proto_defs",
]
