[project]
name = "speech-rec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faster-whisper==1.0.3",
    "numpy>=2.3.5",
    "alicepi-proto @ ../proto_defs",
]
